/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WordleApp {
    }
}
declare global {
    interface HTMLWordleAppElement extends Components.WordleApp, HTMLStencilElement {
    }
    var HTMLWordleAppElement: {
        prototype: HTMLWordleAppElement;
        new (): HTMLWordleAppElement;
    };
    interface HTMLElementTagNameMap {
        "wordle-app": HTMLWordleAppElement;
    }
}
declare namespace LocalJSX {
    interface WordleApp {
    }
    interface IntrinsicElements {
        "wordle-app": WordleApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wordle-app": LocalJSX.WordleApp & JSXBase.HTMLAttributes<HTMLWordleAppElement>;
        }
    }
}
